[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
colored = "2.0.0"
rand = "0.8.5"
strum = { version = "0.24.1", features = ["derive", "strum_macros"] }
